'use strict';
let token='';
const el=id=>document.getElementById(id);
async function api(path,body){const r=await fetch(path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:body?JSON.stringify(body):undefined});const v=await r.json();if(!r.ok)throw Error(v.error||'Demande refusée');return v;}
async function run(f){try{el('message').textContent='';await f();}catch(e){el('message').textContent=e.message;}}
async function refresh(){const data=await api('/admin/licenses');el('list').replaceChildren();for(const l of data.licenses){const p=document.createElement('p');p.textContent=`${l.customer} — ${l.id} — ${l.revoked?'RÉVOQUÉE':'active'} — ${l.max_accounts} compte(s) — expire ${l.expires_at} `;if(!l.revoked){const b=document.createElement('button');b.textContent='Révoquer';b.onclick=()=>{if(confirm('Révoquer cette licence et arrêter ses automatisations ?'))run(async()=>{await api('/admin/licenses/'+encodeURIComponent(l.id)+'/revoke',{});await refresh();});};p.append(b);}for(const i of l.installations){const s=document.createElement('span');s.textContent=` Installation ${i.id} : ${i.disabled?'désactivée':'active'} `;if(!i.disabled){const b=document.createElement('button');b.textContent='Désactiver et libérer ce compte';b.onclick=()=>{if(confirm('Désactiver définitivement cette installation ?'))run(async()=>{await api('/admin/installations/'+encodeURIComponent(i.id)+'/disable',{});await refresh();});};s.append(b);}p.append(s);}el('list').append(p);}}
el('login').onsubmit=e=>{e.preventDefault();run(async()=>{const f=new FormData(e.target);try{token=(await api('/login',Object.fromEntries(f))).token;}finally{e.target.password.value='';}el('admin').hidden=false;el('login').hidden=true;await refresh();});};
el('issue').onsubmit=e=>{e.preventDefault();run(async()=>{const f=Object.fromEntries(new FormData(e.target));f.days=Number(f.days);f.accounts=Number(f.accounts);el('license').value=(await api('/admin/licenses',f)).license;await refresh();});};
el('refresh').onclick=()=>run(refresh);el('logout').onclick=()=>location.reload();
