# Autogenerated: load compressed main from _main_b64_*.txt sidecar files.
import zlib, base64
from pathlib import Path
_dir = Path(__file__).resolve().parent
_parts = sorted(_dir.glob('_main_b64_*.txt'))
if not _parts:
    raise RuntimeError('missing _main_b64_*.txt payloads next to main.py')
_b = ''.join(p.read_text().strip() for p in _parts)
exec(compile(zlib.decompress(base64.b64decode(_b)).decode('utf-8'), __file__, 'exec'), globals())
